# Excelファイル → HTML テーブル変換

In [1]:
import pandas as pd

from funcs.conv import df_to_html

In [2]:
file_body = 'excel/trader_20250227'
file_excel = '%s.xlsm' % file_body
df = pd.read_excel(file_excel, sheet_name='Transaction')
df

  注文番号        時刻   売買      金額     損益  最大益   最大損               備考
0    1  09:10:02   買建  191750    NaN  NaN   NaN   建玉, period = 2
1    1  09:11:21   売埋  191750 -350.0  100  -350  損切１, period = 3
2    2  09:21:01   売建  191200    NaN  NaN   NaN   建玉, period = 3
3    2  09:24:01   買埋  191200 -200.0    0  -200  損切２, period = 6
4    3  09:44:01   買建  191700    NaN  NaN   NaN   建玉, period = 4
5    3  09:46:01   売埋  191700  -50.0    0  -150  損切２, period = 6
6    4  10:09:01   売建  192700    NaN  NaN   NaN   建玉, period = 2
7    4  10:23:01   買埋  192700  250.0  600  -100  返済, period = 15
8  ---       ---  ---    実現損益 -350.0  ---   ---              ---

In [3]:
list_col_format = ['int', 'str', 'str', 'int', 'int', 'int', 'int', 'str']
list_html = df_to_html(df, list_col_format)

file_html = '%s.html' % file_body
with open(file_html, mode='w') as f:
    f.writelines(list_html)