# Excelファイル → HTML テーブル変換

In [1]:
import pandas as pd

from funcs.conv import df_to_html

In [2]:
file_body = 'excel/trader_20250228'
file_excel = '%s.xlsm' % file_body
df = pd.read_excel(file_excel, sheet_name='Transaction')
df

   注文番号        時刻   売買      金額      損益   最大益   最大損               備考
0     1  09:17:02   売建  192250     NaN   NaN   NaN   建玉, period = 1
1     1  09:35:01   買埋  192250  1150.0  1350  -250  返済, period = 18
2     2  09:37:01   買建  191350     NaN   NaN   NaN   建玉, period = 2
3     2  09:42:01   売埋  191350  -250.0   200  -300   返済, period = 6
4     3  10:06:01   売建  190400     NaN   NaN   NaN   建玉, period = 1
5     3  10:11:19   買埋  190400  -350.0   200  -350  損切１, period = 6
6     4  10:30:01   売建  189950     NaN   NaN   NaN   建玉, period = 4
7     4  10:34:13   買埋  189950   150.0   550     0  利確１, period = 8
8     5  13:27:00   買建  190350     NaN   NaN   NaN   建玉, period = 2
9     5  13:47:00   売埋  190350    50.0   150  -200  返済, period = 21
10    6  13:51:00   売建  190150     NaN   NaN   NaN   建玉, period = 4
11    6  14:05:00   買埋  190150    50.0   200  -150  返済, period = 17
12  ---       ---  ---    実現損益   800.0   ---   ---              ---

In [3]:
list_col_format = ['int', 'str', 'str', 'int', 'int', 'int', 'int', 'str']
list_html = df_to_html(df, list_col_format)

file_html = '%s.html' % file_body
with open(file_html, mode='w') as f:
    f.writelines(list_html)