In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame()
df.index.name = '#'

for r in range(30):
    n = r + 1
    x1 = 0.00001 * n
    x2 = x1 * 10
    df.at[n, 'af_init'] = 0
    df.at[n, 'af_step'] = x1
    df.at[n, 'af_max'] = x2

df

    af_init  af_step  af_max
#
1       0.0  0.00001  0.0001
2       0.0  0.00002  0.0002
3       0.0  0.00003  0.0003
4       0.0  0.00004  0.0004
5       0.0  0.00005  0.0005
6       0.0  0.00006  0.0006
7       0.0  0.00007  0.0007
8       0.0  0.00008  0.0008
9       0.0  0.00009  0.0009
10      0.0  0.00010  0.0010
11      0.0  0.00011  0.0011
12      0.0  0.00012  0.0012
13      0.0  0.00013  0.0013
14      0.0  0.00014  0.0014
15      0.0  0.00015  0.0015
16      0.0  0.00016  0.0016
17      0.0  0.00017  0.0017
18      0.0  0.00018  0.0018
19      0.0  0.00019  0.0019
20      0.0  0.00020  0.0020
21      0.0  0.00021  0.0021
22      0.0  0.00022  0.0022
23      0.0  0.00023  0.0023
24      0.0  0.00024  0.0024
25      0.0  0.00025  0.0025
26      0.0  0.00026  0.0026
27      0.0  0.00027  0.0027
28      0.0  0.00028  0.0028
29      0.0  0.00029  0.0029
30      0.0  0.00030  0.0030

In [4]:
file_json = 'doe_af.json'
df.to_json(file_json)

In [5]:
pd.read_json(file_json)

    af_init  af_step  af_max
1         0  0.00001  0.0001
2         0  0.00002  0.0002
3         0  0.00003  0.0003
4         0  0.00004  0.0004
5         0  0.00005  0.0005
6         0  0.00006  0.0006
7         0  0.00007  0.0007
8         0  0.00008  0.0008
9         0  0.00009  0.0009
10        0  0.00010  0.0010
11        0  0.00011  0.0011
12        0  0.00012  0.0012
13        0  0.00013  0.0013
14        0  0.00014  0.0014
15        0  0.00015  0.0015
16        0  0.00016  0.0016
17        0  0.00017  0.0017
18        0  0.00018  0.0018
19        0  0.00019  0.0019
20        0  0.00020  0.0020
21        0  0.00021  0.0021
22        0  0.00022  0.0022
23        0  0.00023  0.0023
24        0  0.00024  0.0024
25        0  0.00025  0.0025
26        0  0.00026  0.0026
27        0  0.00027  0.0027
28        0  0.00028  0.0028
29        0  0.00029  0.0029
30        0  0.00030  0.0030